# File: topic.py

import json
import os
from confluent_kafka import Producer

# Kafka configuration
conf = {'bootstrap.servers': 'localhost:9092'}
producer = Producer(conf)

topic = "iris_clean_topic"

def delivery_report(err, msg):
    if err is not None:
        print(f"Delivery failed: {err}")
    else:
        print(f"Message delivered to {msg.topic()} [{msg.partition()}]")

# Read the JSON file generated by Rest_API.py
if os.path.exists("message_buffer.json"):
    with open("message_buffer.json", "r") as f:
        try:
            record = json.load(f)
            # Publish to Kafka
            producer.produce(
                topic=topic,
                value=json.dumps(record),
                callback=delivery_report
            )
            producer.flush()
            print("Message sent to Kafka.")
        except json.JSONDecodeError:
            print("Invalid JSON in buffer.")
else:
    print("No message found. Please send data using /message endpoint.")
